// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Sq-qH1UTEdePUKjtYdhlkIX1G3yAL2c',
    appId: '1:497643825926:web:689f9aa4adcaeac736cc87',
    messagingSenderId: '497643825926',
    projectId: 'suraksha-setu-68909',
    authDomain: 'suraksha-setu-68909.firebaseapp.com',
    storageBucket: 'suraksha-setu-68909.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXvVzL8Ux5NMvXbxO_m4nofnJeaPYFp7I',
    appId: '1:497643825926:android:497556c48c72b7e936cc87',
    messagingSenderId: '497643825926',
    projectId: 'suraksha-setu-68909',
    storageBucket: 'suraksha-setu-68909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3AbmQ9TTL_TxzoJaJN0ApDYj0UlbyRG0',
    appId: '1:497643825926:ios:11b580cc2d6f1cc236cc87',
    messagingSenderId: '497643825926',
    projectId: 'suraksha-setu-68909',
    storageBucket: 'suraksha-setu-68909.firebasestorage.app',
    iosBundleId: 'com.example.p48',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3AbmQ9TTL_TxzoJaJN0ApDYj0UlbyRG0',
    appId: '1:497643825926:ios:11b580cc2d6f1cc236cc87',
    messagingSenderId: '497643825926',
    projectId: 'suraksha-setu-68909',
    storageBucket: 'suraksha-setu-68909.firebasestorage.app',
    iosBundleId: 'com.example.p48',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Sq-qH1UTEdePUKjtYdhlkIX1G3yAL2c',
    appId: '1:497643825926:web:067f9edf4da13e5536cc87',
    messagingSenderId: '497643825926',
    projectId: 'suraksha-setu-68909',
    authDomain: 'suraksha-setu-68909.firebaseapp.com',
    storageBucket: 'suraksha-setu-68909.firebasestorage.app',
  );
}
